test-arduino:
  image: ubuntu
  script:
    - ./extras/scripts/setup-arduino.sh
    - make verify-examples

test-ubuntu:
  image: ubuntu
  script:
    - ./extras/scripts/setup-devenv.sh
    - make test

