language: cpp
sudo: required

matrix: 
  include:
    # core Arduino library
    - services: docker
      script: docker run --rm -v $(pwd):/workdir ubuntu /bin/bash -c "/workdir/extras/scripts/setup-arduino.sh && make -C /workdir verify-examples"

    # extras on Linux
    - services: docker
      script: docker run --rm -v $(pwd):/workdir ubuntu /bin/bash -c "/workdir/extras/scripts/setup-devenv.sh && make -C /workdir test"

    # extras on Mac
    - os: osx
      osx_image: xcode9.3
      install: brew install glfw3
      script: make test 

