ledr=0.04
# Stage LED strands

# Stage ???
[[strand]]
renderers = [{type="pixelpusher", addr="10.2.0.10", port=7331, strip=0}]
layout = {type="matrix-zigzag", size=[16,4], origin=[14.30, -0.70], resolution=3}

# Stage ???
[[strand]]
renderers = [{type="pixelpusher", addr="10.2.0.10", port=7331, strip=1}]
layout = {type="matrix-zigzag", size=[20,20], origin=[7.50, 0.00], resolution=7}

# Stage ???
[[strand]]
renderers = [{type="pixelpusher", addr="10.2.0.10", port=7331, strip=2}]
layout = {type="matrix-zigzag", size=[20,20], origin=[10.50, 0.00], resolution=7}
