name: Build extras

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: Download and Install GLFW3 Dependency
      run: |
          GLFW_VERSION=$(curl -Ls https://api.github.com/repos/glfw/glfw/releases/latest | grep tag_name | sed 's/.*:[^"]"\([^"]*\)".*/\1/')
          echo ${GLFW_VERSION}
          curl -OLs https://github.com/glfw/glfw/releases/download/${GLFW_VERSION}/glfw-${GLFW_VERSION}.zip
          rm -rf glfw-${GLFW_VERSION} >/dev/null 2>&1
          unzip -q glfw-${GLFW_VERSION}.zip
          cmake -S glfw-${GLFW_VERSION} -B glfw-${GLFW_VERSION}/build
          sudo make -C glfw-${GLFW_VERSION}/build install
    - name: Prepare CMake Files
      run: cmake -S extras -B extras/build
    - name: Build
      run: cmake --build extras/build
