name: Build extras

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: Download GLFW3 Dependency
      run: curl -OL https://github.com/glfw/glfw/releases/download/3.3.9/glfw-3.3.9.zip
    - name: Extract GLFW3 Dependency
      run: unzip glfw-3.3.9.zip
    - name: Prepare GLFW3 Dependency CMake files
      run: cmake -S glfw-3.3.9 -B glfw-3.3.9/build
    - name: Install GLFW3 Dependency
      run: sudo make -C glfw-3.3.9/build install
    - name: Prepare CMake Files
      run: cmake -S extras -B extras/build
    - name: Build
      run: cmake --build extras/build
