name: Build extras

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare CMake Files
      run: cmake -S extras -B extras/build
    - name: Build
      run: cmake --build extras/build
